### ISSUE TITLE
Lists not parsed correctly on http_archive `repos_lock.update` on repos_index file

### ISSUE THREAD

**Issue by michael-sbarra-apexai** [ApexAI/rules_ros#17]
For example:

```yaml
  repo_name:
    version: XXX
    sha256: XXX
    strip_prefix: "repo_name-XXX"
    registry_type: repository
    project_id: XXX
    filename: archive.tar.gz
    type: apex_http_archive
    bazel: {}
    patches: ["//some.patch"]
    patch_args: ["-p1"]
```

Should be parsed as

```py
    _maybe(
        name = "repo_name",
        version = "XXX",
        sha256 = "XXX",
        strip_prefix = "repo_name-XXX,
        registry_type = "repository",
        project_id = "XXX",
        filename = "archive.tar.gz",
        patches = ["some.patch"],
        patch_args = ["-p1"],
        repo_rule = apex_http_archive,
    )
```

But the lists are turned into a single string:

```py
_maybe(
    name = "repo_name",
    version = "XXX",
    sha256 = "XXX",
    strip_prefix = "repo_name-XXX",
    registry_type = "repository",
    project_id = "XXX",
    filename = "archive.tar.gz",
    patches = "['some.patch']",
    patch_args = "['-p1']",
    repo_rule = http_archive,
)
```

When calling `bazel run @rules_ros//repos/config:repos_lock.update`
